//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashZavod.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class access
    {
        public int id_access { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> access1 { get; set; }
        public Nullable<int> id_object { get; set; }
    
        public virtual @object @object { get; set; }
        public virtual users users { get; set; }
    }
}
