//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashZavod.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public doc()
        {
            this.infoFileDoc = new HashSet<infoFileDoc>();
        }
    
        public int id_doc { get; set; }
        public string author { get; set; }
        public string recipient { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> data_of_create { get; set; }
        public Nullable<System.DateTime> date_of_modify { get; set; }
        public Nullable<int> id_edit { get; set; }
    
        public virtual edit edit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<infoFileDoc> infoFileDoc { get; set; }
        public virtual @object @object { get; set; }
    }
}
