//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashZavod.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class edit
    {
        public int id_edit { get; set; }
        public int id_doc { get; set; }
        public Nullable<System.DateTime> date_of_edit { get; set; }
        public string author { get; set; }
        public string edit1 { get; set; }
    
        public virtual doc doc { get; set; }
    }
}
