//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashZavod.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoFileDoc
    {
        public int id_infoFileDoc { get; set; }
        public string url { get; set; }
        public Nullable<int> id_tom { get; set; }
        public Nullable<int> id_doc { get; set; }
        public string text_doc { get; set; }
        public string name_doc { get; set; }
        public string state { get; set; }
    
        public virtual doc doc { get; set; }
        public virtual tom tom { get; set; }
    }
}
