//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashZavod.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class message
    {
        public int id_message { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> id_chat { get; set; }
        public string text_message { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
    
        public virtual chat chat { get; set; }
    }
}
