//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashZavod.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class remider
    {
        public int id_remider { get; set; }
        public Nullable<int> id_author { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_doc { get; set; }
        public string text { get; set; }
        public string visible { get; set; }
    
        public virtual doc doc { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
