//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashZavod.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminders
    {
        public int Id { get; set; }
        public int IdSender { get; set; }
        public int IdRecipient { get; set; }
        public int IdDocument { get; set; }
        public string Text { get; set; }
        public bool Visible { get; set; }
        public System.DateTime DateReminder { get; set; }
    }
}
