//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MashZavod.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_chat
    {
        public int id_user_chat { get; set; }
        public Nullable<int> id_chat { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> @object { get; set; }
    
        public virtual chat chat { get; set; }
        public virtual users users { get; set; }
    }
}
